version: "3.8"

services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - user-service
      - payment-service

  order-service:
    build: ./order-service
    container_name: order-service
   # expose:
    #  - "8080"

  user-service:
    build: ./user-service
    container_name: user-service
   # expose:
    #  - "8080"

  payment-service:
    build: ./payment-service
    container_name: payment-service
   # expose:
   #   - "8080"