apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: user-backendconfig
spec:
  healthCheck:
    requestPath: /users
    port: 8081
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: order-backendconfig
spec:
  healthCheck:
    requestPath: /orders
    port: 8082
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: payment-backendconfig
spec:
  healthCheck:
    requestPath: /health
    port: 8083
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2