management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.application.name=user-service
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
#spring.datasource.username=your_username
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port:8081

# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer config
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest

# (Optional but useful)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer